-- model_matrix gains a structured provider binding (W10-68). A slash in a
-- single string cannot tell a providerId prefix from a vendor-namespaced
-- model id -- `ghost/model` and `qwen/qwen3-coder-next` are the same shape,
-- and no parsing rule distinguishes them (W10-60 had to guess). A row now
-- says which provider it means directly. NULL keeps today's meaning: bind
-- to the single enabled provider, ambiguous if several -- nothing existing
-- has to be requalified by hand.
--
-- Plain `ALTER TABLE ... ADD COLUMN`, not a recreate (W11-10): W10-68's
-- first attempt used this shape and was reshaped into a `CREATE
-- model_matrix_new ... SELECT ... DROP ... RENAME` recreate instead,
-- because the recreate tolerates being re-applied to a db that already has
-- `provider_id` (harmless CREATE-then-copy) where ADD COLUMN throws
-- "duplicate column name". That tolerance was the defect, not a feature:
-- the recreate's `INSERT INTO model_matrix_new (...) SELECT ...` never
-- named `provider_id`, so a "successful" re-application silently reset
-- every row's provider binding to NULL. `applyMigrations`
-- (packages/events/src/migrate.ts) is the sole authority for "has this
-- file already run" via `PRAGMA user_version`, set inside the same
-- transaction as this file's SQL (DATABASE.md §8: forward-only, no down
-- migrations) -- nothing in normal operation re-runs an already-applied
-- migration. `apps/server/src/bootstrap/boot-sequence.test.ts`'s
-- rewound-`user_version` fixture that made this file re-apply during
-- W10-68 was itself the bug: it rolled `user_version` back one version
-- without undoing this file's own schema effect (it undid 012's instead,
-- stale since this file shipped), simulating a schema state that
-- `applyMigrations` never actually produces. That fixture is fixed
-- alongside this file rather than papering over it here again.
ALTER TABLE model_matrix ADD COLUMN provider_id TEXT;
